CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "MemberRole" AS ENUM ('OWNER', 'EDITOR');
CREATE TYPE "PresentationSource" AS ENUM ('TEMPLATE', 'WEB_EDITOR');
CREATE TYPE "ElementType" AS ENUM ('TEXT', 'IMAGE', 'SHAPE');
CREATE TYPE "AnimationPreset" AS ENUM ('FADE_IN', 'SLIDE_UP', 'SLIDE_LEFT', 'ZOOM_IN', 'STAGGER');
CREATE TYPE "ImportStatus" AS ENUM ('UPLOADED', 'QUEUED', 'PROCESSING', 'READY', 'FAILED');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Workspace" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"ownerUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WorkspaceMember" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "MemberRole" NOT NULL DEFAULT 'EDITOR',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WorkspaceMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"createdByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Presentation" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"name" TEXT NOT NULL,"sourceType" "PresentationSource" NOT NULL DEFAULT 'TEMPLATE',"templateKey" TEXT,"accent" TEXT NOT NULL DEFAULT 'violet',"createdByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Presentation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Slide" ("id" TEXT NOT NULL,"presentationId" TEXT NOT NULL,"sortOrder" INTEGER NOT NULL,"title" TEXT,"notes" TEXT,"background" JSONB NOT NULL,"transition" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Slide_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Element" ("id" TEXT NOT NULL,"slideId" TEXT NOT NULL,"sortOrder" INTEGER NOT NULL,"type" "ElementType" NOT NULL,"name" TEXT NOT NULL,"content" JSONB NOT NULL,"position" JSONB NOT NULL,"style" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Element_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Animation" ("id" TEXT NOT NULL,"elementId" TEXT NOT NULL,"preset" "AnimationPreset" NOT NULL,"durationMs" INTEGER NOT NULL DEFAULT 700,"delayMs" INTEGER NOT NULL DEFAULT 0,"easing" TEXT NOT NULL DEFAULT 'easeOut',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Animation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Asset" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"name" TEXT NOT NULL,"url" TEXT NOT NULL,"kind" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Asset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShareLink" ("id" TEXT NOT NULL,"presentationId" TEXT NOT NULL,"token" TEXT NOT NULL,"label" TEXT NOT NULL DEFAULT 'Client share',"coverLabel" TEXT NOT NULL DEFAULT 'Shared presentation',"coverTitle" TEXT,"coverSubtitle" TEXT,"coverButtonText" TEXT NOT NULL DEFAULT 'Enter presentation',"passcodeHash" TEXT,"passcodeEnabled" BOOLEAN NOT NULL DEFAULT false,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ShareLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ImportJob" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"requestedById" TEXT NOT NULL,"presentationId" TEXT,"sourceFilename" TEXT NOT NULL,"sourceMimeType" TEXT NOT NULL,"storedPath" TEXT NOT NULL,"status" "ImportStatus" NOT NULL DEFAULT 'UPLOADED',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ImportJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Workspace_slug_key" ON "Workspace"("slug");
CREATE UNIQUE INDEX "WorkspaceMember_workspaceId_userId_key" ON "WorkspaceMember"("workspaceId", "userId");
CREATE UNIQUE INDEX "Slide_presentationId_sortOrder_key" ON "Slide"("presentationId", "sortOrder");
CREATE UNIQUE INDEX "Element_slideId_sortOrder_key" ON "Element"("slideId", "sortOrder");
CREATE UNIQUE INDEX "Animation_elementId_key" ON "Animation"("elementId");
CREATE UNIQUE INDEX "ShareLink_token_key" ON "ShareLink"("token");
ALTER TABLE "Workspace" ADD CONSTRAINT "Workspace_ownerUserId_fkey" FOREIGN KEY ("ownerUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkspaceMember" ADD CONSTRAINT "WorkspaceMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkspaceMember" ADD CONSTRAINT "WorkspaceMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Presentation" ADD CONSTRAINT "Presentation_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Presentation" ADD CONSTRAINT "Presentation_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Slide" ADD CONSTRAINT "Slide_presentationId_fkey" FOREIGN KEY ("presentationId") REFERENCES "Presentation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Element" ADD CONSTRAINT "Element_slideId_fkey" FOREIGN KEY ("slideId") REFERENCES "Slide"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Animation" ADD CONSTRAINT "Animation_elementId_fkey" FOREIGN KEY ("elementId") REFERENCES "Element"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Asset" ADD CONSTRAINT "Asset_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShareLink" ADD CONSTRAINT "ShareLink_presentationId_fkey" FOREIGN KEY ("presentationId") REFERENCES "Presentation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_presentationId_fkey" FOREIGN KEY ("presentationId") REFERENCES "Presentation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
